apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq
  namespace: roboshop
  labels:
    component: rabbitmq
    project: roboshop
    env: dev 
    tier: database
type: opaque 
data:
  RABBITMQ_DEFAULT_USER: "cm9ib3Nob3A="
  RABBITMQ_DEFAULT_PASS: "cm9ib3Nob3AxMjM="
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-headless
  namespace: roboshop
  labels:
    component: rabbitmq 
    env: dev
    project: roboshop
spec:
  ports:
    - protocol: TCP 
      port: 5672   
      targetPort: 5672
  clusterIP: None
  selector:
    component: rabbitmq 
    env: dev
    project: roboshop
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-svc
  namespace: roboshop
  labels:
    component: rabbitmq 
    env: dev
    project: roboshop
spec:
  selector:
    component: rabbitmq 
    env: dev
    project: roboshop
  ports:
    - protocol: TCP 
      port: 5672   
      targetPort: 5672
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
  namespace: roboshop
spec:
  selector:
    matchLabels:
      component: rabbitmq 
      env: dev
      project: roboshop
  serviceName: "rabbitmq-headless"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        component: rabbitmq 
        env: dev
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3
        envFrom:
          - secretRef:
              name: rabbitmq
        volumeMounts:
        - name: rabbitmq-pvc
          mountPath: /var/lib/rabbitmq
  volumeClaimTemplates:
  - metadata:
      name: rabbitmq-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi