apiVersion: v1
kind: Secret
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql
    project: roboshop
    env: dev 
    tier: database
type: opaque 
data:
  MYSQL_ROOT_PASSWORD: "Um9ib1Nob3BAMQ=="
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  namespace: roboshop
  labels:
    component: mysql 
    env: dev
    project: roboshop
spec:
  ports:
    - protocol: TCP 
      port: 3306   
      targetPort: 3306
  clusterIP: None
  selector:
    component: mysql 
    env: dev
    project: roboshop
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
  labels:
    component: mysql 
    env: dev
    project: roboshop
spec:
  selector:
    component: mysql 
    env: dev
    project: roboshop
  ports:
    - protocol: TCP 
      port: 3306   
      targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    matchLabels:
      component: mysql 
      env: dev
      project: roboshop
  serviceName: "mysql-headless"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        component: mysql 
        env: dev
        project: roboshop # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: mysql
        image: shanmukhatadisetti/mysql:v1
        envFrom:
          - secretRef:
              name: mysql
        volumeMounts:
        - name: mysql-pvc
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: mysql-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "roboshop-ebs"
      resources:
        requests:
          storage: 2Gi